courseproject/Models/Цеха_производства.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace courseproject.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Цеха_производства
    {
        public int ID_объекта { get; set; }
        public int Кол_во_сотрудников { get; set; }
        public Nullable<int> ID_начальника_цеха { get; set; }
        public int Общий_объем_инкубаторов { get; set; }
        public int Объем_продукции_в_сутки { get; set; }
    
        public virtual Объекты Объекты { get; set; }
        public virtual Сотрудники Сотрудники { get; set; }
    }
}

courseproject/Controllers/ОбъектыController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using courseproject.Models;

namespace courseproject.Controllers
{
    public class ОбъектыController : Controller
    {
        private factoryEntities db = new factoryEntities();

        // GET: Объекты
        public ActionResult Index()
        {
            var объекты = db.Объекты.Include(о => о.Склады).Include(о => о.Цеха_производства);
            return View(объекты.ToList());
        }

        // GET: Объекты/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Объекты объекты = db.Объекты.Find(id);
            if (объекты == null)
            {
                return HttpNotFound();
            }
            return View(объекты);
        }

        // GET: Объекты/Create
        public ActionResult Create()
        {
            ViewBag.ID_объекта = new SelectList(db.Склады, "ID_объекта", "ID_объекта");
            ViewBag.ID_объекта = new SelectList(db.Цеха_производства, "ID_объекта", "ID_объекта");
            return View();
        }

        // POST: Объекты/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_объекта,Наименование,Площадь,Влажность,Наличие_морозильных_камер,Температура")] Объекты объекты)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Объекты.Add(объекты);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ID_объекта = new SelectList(db.Склады, "ID_объекта", "ID_объекта", объекты.ID_объекта);
                ViewBag.ID_объекта = new SelectList(db.Цеха_производства, "ID_объекта", "ID_объекта", объекты.ID_объекта);
                return View(объекты);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { code = 1 });
            }
        }

        // GET: Объекты/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Объекты объекты = db.Объекты.Find(id);
            if (объекты == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_объекта = new SelectList(db.Склады, "ID_объекта", "ID_объекта", объекты.ID_объекта);
            ViewBag.ID_объекта = new SelectList(db.Цеха_производства, "ID_объекта", "ID_объекта", объекты.ID_объекта);
            return View(объекты);
        }

        // POST: Объекты/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_объекта,Наименование,Площадь,Влажность,Наличие_морозильных_камер,Температура")] Объекты объекты)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(объекты).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ID_объекта = new SelectList(db.Склады, "ID_объекта", "ID_объекта", объекты.ID_объекта);
                ViewBag.ID_объекта = new SelectList(db.Цеха_производства, "ID_объекта", "ID_объекта", объекты.ID_объекта);
                return View(объекты);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { code = 2 });
            }
        }

        // GET: Объекты/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Объекты объекты = db.Объекты.Find(id);
            if (объекты == null)
            {
                return HttpNotFound();
            }
            return View(объекты);
        }

        // POST: Объекты/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Объекты объекты = db.Объекты.Find(id);
            db.Объекты.Remove(объекты);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

courseproject/Controllers/Цеха_производстваController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using courseproject.Models;

namespace courseproject.Controllers
{
    public class Цеха_производстваController : Controller
    {
        private factoryEntities db = new factoryEntities();

        // GET: Цеха_производства
        public ActionResult Index()
        {
            var цеха_производства = db.Цеха_производства.Include(ц => ц.Объекты).Include(ц => ц.Сотрудники);
            return View(цеха_производства.ToList());
        }

        // GET: Цеха_производства/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Цеха_производства цеха_производства = db.Цеха_производства.Find(id);
            if (цеха_производства == null)
            {
                return HttpNotFound();
            }
            return View(цеха_производства);
        }

        // GET: Цеха_производства/Create
        public ActionResult Create()
        {
            ViewBag.ID_объекта = new SelectList(db.Объекты, "ID_объекта", "Наименование");
            //ViewBag.ID_начальника_цеха = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия");
            List<SelectListItem> items = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия").ToList();
            items.Insert(0, (new SelectListItem { Text = "null", Value = "" }));
            ViewBag.ID_начальника_цеха = items;
            return View();
        }

        // POST: Цеха_производства/Create
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID_объекта,Кол_во_сотрудников,ID_начальника_цеха,Общий_объем_инкубаторов,Объем_продукции_в_сутки")] Цеха_производства цеха_производства)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Цеха_производства.Add(цеха_производства);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.ID_объекта = new SelectList(db.Объекты, "ID_объекта", "Наименование", цеха_производства.ID_объекта);
                //ViewBag.ID_начальника_цеха = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия", цеха_производства.ID_начальника_цеха);
                List<SelectListItem> items = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия", цеха_производства.ID_начальника_цеха).ToList();
                items.Insert(0, (new SelectListItem { Text = "null", Value = "" }));
                ViewBag.ID_начальника_цеха = items;
                return View(цеха_производства);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { code = 1 });
            }
        }

        // GET: Цеха_производства/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Цеха_производства цеха_производства = db.Цеха_производства.Find(id);
            if (цеха_производства == null)
            {
                return HttpNotFound();
            }
            ViewBag.ID_объекта = new SelectList(db.Объекты, "ID_объекта", "Наименование", цеха_производства.ID_объекта);
            //ViewBag.ID_начальника_цеха = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия", цеха_производства.ID_начальника_цеха);
            List<SelectListItem> items = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия", цеха_производства.ID_начальника_цеха).ToList();
            items.Insert(0, (new SelectListItem { Text = "null", Value = "" }));
            ViewBag.ID_начальника_цеха = items;
            return View(цеха_производства);
        }

        // POST: Цеха_производства/Edit/5
        // Чтобы защититься от атак чрезмерной передачи данных, включите определенные свойства, для которых следует установить привязку. Дополнительные 
        // сведения см. в разделе https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID_объекта,Кол_во_сотрудников,ID_начальника_цеха,Общий_объем_инкубаторов,Объем_продукции_в_сутки")] Цеха_производства цеха_производства)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(цеха_производства).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.ID_объекта = new SelectList(db.Объекты, "ID_объекта", "Наименование", цеха_производства.ID_объекта);
                //ViewBag.ID_начальника_цеха = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия", цеха_производства.ID_начальника_цеха);
                List<SelectListItem> items = new SelectList(db.Сотрудники, "ID_сотрудника", "Фамилия", цеха_производства.ID_начальника_цеха).ToList();
                items.Insert(0, (new SelectListItem { Text = "null", Value = "" }));
                ViewBag.ID_начальника_цеха = items;
                return View(цеха_производства);
            }
            catch (Exception)
            {
                return RedirectToAction("Error", "Home", new { code = 2 });
            }
        }

        // GET: Цеха_производства/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Цеха_производства цеха_производства = db.Цеха_производства.Find(id);
            if (цеха_производства == null)
            {
                return HttpNotFound();
            }
            return View(цеха_производства);
        }

        // POST: Цеха_производства/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Цеха_производства цеха_производства = db.Цеха_производства.Find(id);
            db.Цеха_производства.Remove(цеха_производства);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

courseproject/Views/Цеха_производства/Create.cshtml
@model courseproject.Models.Цеха_производства

@{
    ViewBag.Title = "Добавление";
}

<h2>Добавление</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Цеха_производства</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.ID_объекта, "ID_объекта", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_объекта", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_объекта, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Кол_во_сотрудников, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Кол_во_сотрудников, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Кол_во_сотрудников, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_начальника_цеха, "ID_начальника_цеха", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_начальника_цеха", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_начальника_цеха, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Общий_объем_инкубаторов, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Общий_объем_инкубаторов, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Общий_объем_инкубаторов, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Объем_продукции_в_сутки, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Объем_продукции_в_сутки, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Объем_продукции_в_сутки, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Добавить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

courseproject/Views/Цеха_производства/Delete.cshtml
@model courseproject.Models.Цеха_производства

@{
    ViewBag.Title = "Удаление";
}

<h2>Удаление</h2>

<h3>Вы действительно хотите удалить эту запись из таблицы?</h3>
<div>
    <h4>Цеха_производства</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.ID_объекта)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ID_объекта)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Объекты.Наименование)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Объекты.Наименование)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Кол_во_сотрудников)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Кол_во_сотрудников)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Общий_объем_инкубаторов)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Общий_объем_инкубаторов)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Объем_продукции_в_сутки)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Объем_продукции_в_сутки)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Сотрудники.Фамилия) начальника цеха
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Сотрудники.Фамилия)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Удалить" class="btn btn-default" /> |
            @Html.ActionLink("Назад", "Index")
        </div>
    }
</div>

courseproject/Views/Цеха_производства/Details.cshtml
@model courseproject.Models.Цеха_производства

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Цеха_производства</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Кол_во_сотрудников)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Кол_во_сотрудников)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Общий_объем_инкубаторов)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Общий_объем_инкубаторов)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Ср__объем_продукции_в_сутки)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Ср__объем_продукции_в_сутки)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Объекты.Наименование)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Объекты.Наименование)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Сотрудники.Фамилия)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Сотрудники.Фамилия)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.ID_объекта }) |
    @Html.ActionLink("Back to List", "Index")
</p>

courseproject/Views/Цеха_производства/Edit.cshtml
@model courseproject.Models.Цеха_производства

@{
    ViewBag.Title = "Изменение";
}

<h2>Изменение</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Цеха_производства</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID_объекта)

        <div class="form-group">
            @Html.LabelFor(model => model.Кол_во_сотрудников, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Кол_во_сотрудников, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Кол_во_сотрудников, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ID_начальника_цеха, "ID_начальника_цеха", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("ID_начальника_цеха", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.ID_начальника_цеха, "", new { @class = "text-danger" })
            </div>
            <span style="font-style: italic;">*Выбирается в зависимости от выбранной Фамилии сотрудника.</span>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Общий_объем_инкубаторов, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Общий_объем_инкубаторов, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Общий_объем_инкубаторов, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Объем_продукции_в_сутки, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Объем_продукции_в_сутки, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Объем_продукции_в_сутки, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Сохранить" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Назад", "Index")
</div>

courseproject/Views/Цеха_производства/Index.cshtml
@model IEnumerable<courseproject.Models.Цеха_производства>

@{
    ViewBag.Title = "Цеха производства";
}

<h2>Цеха производства птицефабрики</h2>
<p style="font-style:italic; margin-top: 10px;">*Каждый цех является одним из объектов птицефабрики.</p>
<p style="font-style:italic; margin-top: 10px;">Общая информация относительно объектов находится в таблице @Html.ActionLink("\"Объекты\".", "Index", "Объекты")</p>

<p>
    @Html.ActionLink("Добавить новый", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.ID_объекта)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Объекты.Наименование)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Кол_во_сотрудников)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Общий_объем_инкубаторов)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Объем_продукции_в_сутки)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Сотрудники.Фамилия) начальника цеха
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
<tr>
    <td>
        @Html.DisplayFor(modelItem => item.ID_объекта)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Объекты.Наименование)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Кол_во_сотрудников)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Общий_объем_инкубаторов)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Объем_продукции_в_сутки)
    </td>
    <td>
        @Html.DisplayFor(modelItem => item.Сотрудники.Фамилия)
    </td>
    <td>
        @Html.ActionLink("Изменить", "Edit", new { id = item.ID_объекта }) |
        @Html.ActionLink("Удалить", "Delete", new { id = item.ID_объекта })
    </td>
</tr>
    }

</table>